swagger_url = "https://api.zknft.findora.org"
listen_address = "0.0.0.0"
listen_port = 8888
findora_query_url = "https://prod-testnet.prod.findora.org:8668"
web3_http_url = "https://goerli.infura.io/v3/06fb6ba2d54943cbb52c7d84929b0c28"
contract_address = "0xF89fC6F1C9595AF8578CafDed71796F3615CB2eF"
dir_path = "/data"