swagger_url = "http://127.0.0.1:8888"
listen_address = "0.0.0.0"
listen_port = 8888
findora_query_url = "https://prod-mainnet.prod.findora.org:8668"
web3_http_url = "http://127.0.0.1:8545"
contract_address = "0xbD694Bf489eE062d0b18da456177Ba623dcDEbF9"
